create unique index if not exists hadith_collection_num_uq on hadith (collection, hadith_num);
with base as (select coalesce(max(id), 0) as m from hadith),
v (arabic_text, translation, collection, hadith_num, grading) as (values
  ('إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ',
   'Actions are but by intentions, and every man shall have only that which he intended.',
   'Bukhari & Muslim', 1, 'Sahih'),
  ('الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
   'A Muslim is the one from whose tongue and hand the Muslims are safe.',
   'Bukhari', 10, 'Sahih'),
  ('لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
   'None of you truly believes until he loves for his brother what he loves for himself.',
   'Bukhari & Muslim', 13, 'Sahih'),
  ('مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
   'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
   'Bukhari & Muslim', 47, 'Sahih'),
  ('الطُّهُورُ شَطْرُ الإِيمَانِ',
   'Purity is half of faith.',
   'Muslim', 223, 'Sahih'),
  ('الدِّينُ النَّصِيحَةُ',
   'The religion is sincere advice (naseehah).',
   'Muslim', 55, 'Sahih'),
  ('مَنْ لاَ يَرْحَمُ النَّاسَ لاَ يَرْحَمُهُ اللَّهُ',
   'He who does not show mercy to people, Allah will not show mercy to him.',
   'Bukhari & Muslim', 5997, 'Sahih'),
  ('اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ',
   'Fear Allah wherever you are, follow a bad deed with a good deed which will wipe it out, and treat people with good character.',
   'Tirmidhi', 1987, 'Hasan'),
  ('لاَ تَغْضَبْ',
   'Do not become angry.',
   'Bukhari', 6116, 'Sahih'),
  ('الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ',
   'A good word is charity.',
   'Bukhari & Muslim', 2989, 'Sahih'),
  ('تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
   'Your smile for your brother is a charity.',
   'Tirmidhi', 1956, 'Hasan'),
  ('مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
   'Whoever travels a path in search of knowledge, Allah will make easy for him a path to Paradise.',
   'Muslim', 2699, 'Sahih'),
  ('خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
   'The best of you are those who learn the Qur’an and teach it.',
   'Bukhari', 5027, 'Sahih'),
  ('مَنْ صَمَتَ نَجَا',
   'Whoever remains silent is saved.',
   'Tirmidhi', 2501, 'Hasan'),
  ('الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ',
   'The strong believer is better and more beloved to Allah than the weak believer, though both are good.',
   'Muslim', 2664, 'Sahih'),
  (null, 'Islam is built upon five: the testimony that none is worthy of worship but Allah and that Muhammad is His Messenger, establishing prayer, giving zakat, the pilgrimage, and fasting Ramadan.',
   'An-Nawawi 40', 3, 'Sahih'),
  (null, 'Part of the perfection of Islam is leaving that which does not concern one.',
   'An-Nawawi 40', 12, 'Hasan'),
  (null, 'Leave that which makes you doubt for that which does not make you doubt.',
   'An-Nawawi 40', 11, 'Sahih'),
  (null, 'Verily Allah is Pure and accepts only that which is pure.',
   'An-Nawawi 40', 10, 'Sahih'),
  (null, 'What I have forbidden you, avoid, what I have ordered you, do as much of it as you can.',
   'An-Nawawi 40', 9, 'Sahih'),
  (null, 'Allah has laid down religious duties, so do not neglect them, He has set limits, so do not overstep them.',
   'An-Nawawi 40', 30, 'Hasan'),
  (null, 'Be in this world as though you were a stranger or a wayfarer.',
   'An-Nawawi 40', 40, 'Sahih'),
  (null, 'Do not become angry, and Paradise is yours.',
   'An-Nawawi 40', 16, 'Sahih'),
  (null, 'Allah has prescribed excellence (ihsan) in all things.',
   'An-Nawawi 40', 17, 'Sahih'),
  (null, 'Be mindful of Allah and He will protect you, be mindful of Allah and you will find Him before you.',
   'An-Nawawi 40', 19, 'Hasan'),
  (null, 'If you feel no shame, then do as you wish.',
   'An-Nawawi 40', 20, 'Sahih'),
  (null, 'Say: I believe in Allah, and then be steadfast (istiqamah).',
   'An-Nawawi 40', 21, 'Sahih'),
  (null, 'The lawful is clear and the unlawful is clear, and between them are doubtful matters.',
   'An-Nawawi 40', 6, 'Sahih'),
  (null, 'Whoever introduces into this affair of ours something that is not from it will have it rejected.',
   'An-Nawawi 40', 5, 'Sahih'),
  (null, 'The most beloved of deeds to Allah are those done consistently, even if they are few.',
   'Riyad as-Salihin', 142, 'Sahih'),
  (null, 'Make things easy and do not make them difficult, give glad tidings and do not repel people.',
   'Riyad as-Salihin', 637, 'Sahih'),
  (null, 'Whoever relieves a believer of a hardship of this world, Allah will relieve him of a hardship on the Day of Resurrection.',
   'Riyad as-Salihin', 245, 'Sahih'),
  (null, 'The believers, in their mutual mercy, love and compassion, are like one body: when a limb suffers, the whole body responds with sleeplessness and fever.',
   'Riyad as-Salihin', 222, 'Sahih'),
  (null, 'None of you should belittle any act of kindness, even meeting your brother with a cheerful face.',
   'Riyad as-Salihin', 121, 'Sahih'),
  (null, 'Richness is not in having many possessions, true richness is the richness of the soul.',
   'Riyad as-Salihin', 517, 'Sahih'),
  (null, 'Whoever believes in Allah and the Last Day, let him honour his guest.',
   'Riyad as-Salihin', 313, 'Sahih'),
  (null, 'Whoever believes in Allah and the Last Day, let him maintain good relations with his relatives.',
   'Riyad as-Salihin', 319, 'Sahih'),
  (null, 'Kind speech and forgiveness are better than charity followed by injury.',
   'Riyad as-Salihin', 700, 'Sahih'),
  (null, 'Fear Allah and treat your children with equal fairness.',
   'Riyad as-Salihin', 296, 'Sahih'),
  (null, 'The best of you are those who are best to their families.',
   'Riyad as-Salihin', 278, 'Sahih'),
  (null, 'He who does not thank people has not thanked Allah.',
   'Riyad as-Salihin', 1345, 'Sahih'),
  (null, 'Charity does not decrease wealth.',
   'Riyad as-Salihin', 557, 'Sahih'),
  (null, 'Whoever conceals the faults of a Muslim, Allah will conceal his faults in this world and the next.',
   'Riyad as-Salihin', 240, 'Sahih'),
  (null, 'Do not envy one another, do not hate one another, do not turn away from one another, be servants of Allah as brothers.',
   'Riyad as-Salihin', 1569, 'Sahih'),
  (null, 'Religion is easy, and no one overburdens himself in his religion but it will overpower him.',
   'Bukhari', 39, 'Sahih'),
  (null, 'Whoever does not give up false speech and acting upon it, Allah has no need of his giving up food and drink.',
   'Bukhari', 1903, 'Sahih'),
  (null, 'The most hated of permissible things to Allah is divorce.',
   'Bukhari', 5265, 'Sahih'),
  (null, 'A man is upon the religion of his close friend, so let each of you look at whom he befriends.',
   'Abu Dawud', 4833, 'Hasan'),
  (null, 'Whoever builds a mosque for Allah, Allah will build for him a house in Paradise.',
   'Bukhari', 450, 'Sahih'),
  (null, 'The upper hand is better than the lower hand, the upper hand is the one that gives.',
   'Bukhari', 1429, 'Sahih'),
  (null, 'Beware of suspicion, for suspicion is the falsest of speech.',
   'Bukhari', 6064, 'Sahih'),
  (null, 'None of you should wish for death because of a calamity that has befallen him.',
   'Bukhari', 5671, 'Sahih'),
  (null, 'Whoever guarantees me what is between his jaws and his legs, I guarantee him Paradise.',
   'Bukhari', 6474, 'Sahih'),
  (null, 'The two feet of the son of Adam will not move on the Day of Resurrection until he is asked about his life, his knowledge, his wealth and his body.',
   'Tirmidhi', 2417, 'Hasan'),
  (null, 'Convey from me, even if it is one verse.',
   'Bukhari', 3461, 'Sahih'),
  (null, 'Whoever takes a path in pursuit of knowledge, Allah makes easy for him a path to Paradise.',
   'Bukhari', 100, 'Sahih'),
  (null, 'The seeking of knowledge is an obligation upon every Muslim.',
   'Ibn Majah', 224, 'Hasan'),
  (null, 'When a man dies, his deeds end except three: an ongoing charity, beneficial knowledge, or a righteous child who prays for him.',
   'Muslim', 1631, 'Sahih'),
  (null, 'Whoever calls to guidance will have a reward like the rewards of those who follow him, without it diminishing theirs.',
   'Muslim', 2674, 'Sahih'),
  (null, 'Every act of goodness is charity.',
   'Muslim', 1005, 'Sahih'),
  (null, 'Modesty brings nothing but good.',
   'Muslim', 37, 'Sahih'),
  (null, 'Whoever guides someone to good will have a reward like the one who does it.',
   'Muslim', 1893, 'Sahih'),
  (null, 'A believer is not stung twice from the same hole.',
   'Muslim', 2998, 'Sahih'),
  (null, 'Supplication is the essence of worship.',
   'Tirmidhi', 3371, 'Hasan'),
  (null, 'The closest a servant comes to his Lord is when he is prostrating, so make abundant supplication then.',
   'Muslim', 482, 'Sahih'),
  (null, 'When one of you loves his brother, let him tell him that he loves him.',
   'Abu Dawud', 5124, 'Sahih'),
  (null, 'Cleanliness is half of faith, and Alhamdulillah fills the scale.',
   'Muslim', 224, 'Sahih'),
  (null, 'The best of the believers in faith is the best of them in character.',
   'Abu Dawud', 4682, 'Sahih'),
  (null, 'Whoever does not show mercy will not be shown mercy.',
   'Muslim', 2318, 'Sahih'),
  (null, 'Allah does not look at your appearances or wealth, but He looks at your hearts and your deeds.',
   'Muslim', 2564, 'Sahih'),
  (null, 'Every one of you is a shepherd and is responsible for his flock.',
   'Bukhari', 893, 'Sahih'),
  (null, 'A kind word and giving food, and greeting with peace whom you know and whom you do not know.',
   'Bukhari', 12, 'Sahih'),
  (null, 'Give the labourer his wages before his sweat dries.',
   'Ibn Majah', 2443, 'Hasan'),
  (null, 'Verily, honesty leads to righteousness, and righteousness leads to Paradise.',
   'Bukhari & Muslim', 6094, 'Sahih'),
  (null, 'The best of you is he who is best to his wife.',
   'Tirmidhi', 3895, 'Sahih'),
  (null, 'Fear Allah regarding the women, for you have taken them as a trust from Allah.',
   'Muslim', 1218, 'Sahih'),
  (null, 'Whoever is not merciful to people, Allah will not be merciful to him.',
   'Tirmidhi', 1922, 'Sahih'),
  (null, 'The best charity is that given when one is in need and struggling.',
   'Abu Dawud', 1677, 'Hasan'),
  (null, 'The dua of a Muslim for his brother in his absence is answered.',
   'Muslim', 2733, 'Sahih'),
  (null, 'Fear the supplication of the oppressed, for there is no barrier between it and Allah.',
   'Bukhari', 1496, 'Sahih'),
  (null, 'Whoever is deprived of gentleness is deprived of all good.',
   'Muslim', 2592, 'Sahih'),
  (null, 'Gentleness is not found in anything except that it beautifies it.',
   'Muslim', 2594, 'Sahih'),
  (null, 'The most complete of the believers in faith are those with the best character and who are kindest to their families.',
   'Tirmidhi', 1162, 'Sahih'),
  (null, 'Smiling in the face of your brother is charity, commanding good and forbidding evil is charity.',
   'Tirmidhi', 2008, 'Hasan'),
  (null, 'Remember often the destroyer of pleasures: death.',
   'Tirmidhi', 2307, 'Hasan'),
  (null, 'Take advantage of five before five: your youth before old age, your health before sickness, your wealth before poverty, your free time before your busyness, and your life before your death.',
   'Al-Hakim', 7846, 'Sahih'),
  (null, 'This world is the prison of the believer and the paradise of the disbeliever.',
   'Muslim', 2956, 'Sahih'),
  (null, 'The strong is not the one who overcomes people by his strength, but the one who controls himself while in anger.',
   'Bukhari', 6114, 'Sahih'),
  (null, 'Whoever suppresses his anger while able to act upon it, Allah will fill his heart with contentment on the Day of Resurrection.',
   'Abu Dawud', 4777, 'Hasan'),
  (null, 'Two words light on the tongue, heavy on the scale, beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-Azim.',
   'Bukhari', 6406, 'Sahih'),
  (null, 'Whoever says SubhanAllahi wa bihamdihi one hundred times a day, his sins are wiped away even if they were like the foam of the sea.',
   'Bukhari', 6405, 'Sahih'),
  (null, 'The best remembrance is La ilaha illallah, and the best supplication is Alhamdulillah.',
   'Tirmidhi', 3383, 'Hasan'),
  (null, 'Whoever sends blessings upon me once, Allah sends blessings upon him tenfold.',
   'Muslim', 384, 'Sahih'),
  (null, 'The prayer that is heaviest upon the hypocrites is the Isha and the Fajr prayer.',
   'Bukhari', 657, 'Sahih'),
  (null, 'The first matter a servant will be brought to account for on the Day of Judgement is the prayer.',
   'Tirmidhi', 413, 'Sahih'),
  (null, 'Between a man and disbelief and paganism is the abandonment of prayer.',
   'Muslim', 82, 'Sahih'),
  (null, 'The key to Paradise is prayer, and the key to prayer is purification.',
   'Tirmidhi', 4, 'Hasan'),
  (null, 'Fasting is a shield.',
   'Bukhari', 1894, 'Sahih'),
  (null, 'Whoever fasts Ramadan out of faith and seeking reward, his previous sins are forgiven.',
   'Bukhari', 38, 'Sahih'),
  (null, 'Hasten to break the fast, for the people will remain upon good as long as they hasten the iftar.',
   'Bukhari', 1957, 'Sahih'),
  (null, 'Whoever gives charity equal to a date from good earnings — Allah accepts it and nurtures it as one of you raises a foal.',
   'Bukhari', 1410, 'Sahih'),
  (null, 'Sadaqah extinguishes sin as water extinguishes fire.',
   'Tirmidhi', 2616, 'Sahih'),
  (null, 'The best of people are those most beneficial to people.',
   'Al-Mujam al-Awsat', 5787, 'Hasan'),
  (null, 'Facilitate and do not make difficult, bring glad tidings and do not drive people away.',
   'Muslim', 1734, 'Sahih'),
  (null, 'How wonderful is the affair of the believer: all of it is good — if good befalls him he is grateful, and if harm befalls him he is patient.',
   'Muslim', 2999, 'Sahih'),
  (null, 'No fatigue, illness, anxiety, sorrow, harm or grief befalls a Muslim but that Allah expiates some of his sins by it.',
   'Bukhari', 5641, 'Sahih'),
  (null, 'Whoever loves to meet Allah, Allah loves to meet him.',
   'Bukhari', 6507, 'Sahih'),
  (null, 'Verily, with hardship comes ease — and the greatest reward comes with the greatest trial.',
   'Tirmidhi', 2396, 'Hasan'),
  (null, 'Allah is more pleased with the repentance of His servant than a man who finds his lost camel in a barren land.',
   'Bukhari', 6309, 'Sahih'),
  (null, 'All the children of Adam constantly err, and the best of those who err are those who repent.',
   'Tirmidhi', 2499, 'Hasan'),
  (null, 'Whoever seeks forgiveness abundantly, Allah will make for him a way out of every distress and provide for him from where he does not expect.',
   'Abu Dawud', 1518, 'Hasan'),
  (null, 'Whoever meets Allah without associating anything with Him will enter Paradise.',
   'Muslim', 93, 'Sahih'),
  (null, 'Speak good or remain silent, honour your neighbour and honour your guest.',
   'Bukhari', 6018, 'Sahih'),
  (null, 'Do not belittle any good deed, even pouring water from your bucket into the vessel of one who asks.',
   'Muslim', 2626, 'Sahih'),
  (null, 'Modesty and faith are companions, when one is lifted, the other goes too.',
   'Al-Hakim', 58, 'Hasan'),
  (null, 'A good companion and a bad one are like a seller of musk and the bellows of a blacksmith.',
   'Bukhari', 5534, 'Sahih'),
  (null, 'The truthful and trustworthy merchant will be with the Prophets, the truthful, and the martyrs.',
   'Tirmidhi', 1209, 'Hasan'),
  (null, 'Whoever removes a worldly grief from a believer, Allah will remove from him one of the griefs of the Day of Resurrection.',
   'Muslim', 2580, 'Sahih'),
  (null, 'Make the remembrance of Allah moist upon your tongue.',
   'Tirmidhi', 3375, 'Hasan')
)
insert into hadith (id, arabic_text, translation, collection, hadith_num, grading)
select b.m + row_number() over (), v.arabic_text, v.translation, v.collection, v.hadith_num, v.grading
from v cross join base b
on conflict (collection, hadith_num) do update set
  arabic_text = excluded.arabic_text,
  translation = excluded.translation,
  grading = excluded.grading;
